FROM ubuntu:latest AS build

RUN apt-get update
RUN apt-get install openjdk-21-jdk -y
COPY pom.xml .
COPY src ./src

RUN apt-get install maven -y
RUN mvn clean install

FROM eclipse-temurin:21-jdk-alpine

EXPOSE 8080

COPY --from=build /target/ConsumoCep-0.0.1-SNAPSHOT.jar app.jar

ENTRYPOINT [ "java", "-jar", "app.jar" ]

